language: python

python:
    - 2.7

sudo: false

env:
    - DJANGO=1.8.18
    - DJANGO=1.9.13
    - DJANGO=1.10.7
    - DJANGO=1.11.3

before_install:
    - bash bin/check_signoff.sh
    - pip install -q flake8
    - flake8

install:
    - pip install -q coverage Django==$DJANGO

script:
    - coverage run test_suite.py

after_success:
    - pip install -q coveralls
    - coveralls
